name: Download and push updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # Every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download and Extract latest release bundle
      run: |
        mkdir -p out
        curl -L https://github.com/thegeeklab/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz | tar -xz -C out/ --strip-components=1
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: out
        publish_branch: output
