name: Build theme

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: src/package-lock.json
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - run: npm ci
      - run: npm run build
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install asciidoctor
      - name: Test build website
        run: |
          alias asciidoctor="asciidoctor --attribute=experimental=true --attribute=icons=font"
          mkdir -p exampleSite/themes/ && ln -s $(pwd)/ exampleSite/themes/hugo-geekdoc
          hugo --panicOnWarning -s exampleSite/ -b http://localhost/
      - name: package
        run: |
          mkdir -p ../out
          tar -cf - -X .tarignore . | tar -xvf - -C ../out
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          publish_branch: output
