name: Download and push updates

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - run: npm ci
      - run: npm run build
      - name: Test build website
        run: |
          mkdir -p exampleSite/themes/ && ln -s $(pwd)/ exampleSite/themes/hugo-geekdoc
          hugo --panicOnWarning -s exampleSite/ -b http://localhost/
      - name: package
        run: |
          mkdir -p ../out
          tar -cf - -X .tarignore . | tar -xvf - -C ../out
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          publish_branch: output
